//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DraftProspects.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DraftProspects.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank,Name,College,Year,Height,Position,GamesPlayed,Goals,Assists,Points,PPGAvg
        ///1,Will Smith, Boston College (Hockey East),Fr.,6-0,F,41,25,46,71,1.73
        ///2,Macklin Celebrini, Boston U. (Hockey East),Fr.,6-0,F,38,32,32,64,1.68
        ///3,Gabe Perreault, Boston College (Hockey East),Fr.,5-11,F,36,19,41,60,1.67
        ///4,Cutter Gauthier, Boston College (Hockey East),So.,6-2,F,41,38,27,65,1.59
        ///5,Jackson Blake, North Dakota (NCHC),So.,5-11,F,40,22,38,60,1.50
        ///6,Ryan Leonard, Boston College (Hockey East),Fr.,6-0,F,41,31,29,60,1.46
        ///7,Ru [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NCAA_Statistics_2023_2024___Division_1 {
            get {
                return ResourceManager.GetString("NCAA Statistics 2023-2024 - Division 1", resourceCulture);
            }
        }
    }
}
